# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - employee-leave

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://registryelms.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e3ccdb457aa3463a92b15bfc4f000a87 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f41e4f9017954545897c11e124a4ea88 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registryelms.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e3ccdb457aa3463a92b15bfc4f000a87 }}/elms:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'employee-leave'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4457a1d10a1d4406855d8c0cff4b128f }}
        images: 'registryelms.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e3ccdb457aa3463a92b15bfc4f000a87 }}/elms:${{ github.sha }}'